{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "043b68d9-3186-4e32-9102-70daeca59e6e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# visitor_tracker.py\n",
    "import sqlite3\n",
    "import datetime\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "DB_FILE = \"visitors.db\"  # 資料庫檔案名稱\n",
    "\n",
    "def init_db():\n",
    "    \"\"\"建立資料表\"\"\"\n",
    "    conn = sqlite3.connect(DB_FILE)\n",
    "    c = conn.cursor()\n",
    "    c.execute('''\n",
    "        CREATE TABLE IF NOT EXISTS visitors (\n",
    "            id INTEGER PRIMARY KEY AUTOINCREMENT,\n",
    "            date TEXT,\n",
    "            user_id TEXT\n",
    "        )\n",
    "    ''')\n",
    "    conn.commit()\n",
    "    conn.close()\n",
    "\n",
    "def record_visit(user_id):\n",
    "    \"\"\"記錄使用者訪問\"\"\"\n",
    "    today = datetime.date.today()\n",
    "    conn = sqlite3.connect(DB_FILE)\n",
    "    c = conn.cursor()\n",
    "\n",
    "    # 檢查是否已經有相同user_id\n",
    "    c.execute('SELECT * FROM visitors WHERE date = ? AND user_id = ?', (today.isoformat(), user_id))\n",
    "    if not c.fetchone():\n",
    "        c.execute('INSERT INTO visitors (date, user_id) VALUES (?, ?)', (today.isoformat(), user_id))\n",
    "        conn.commit()\n",
    "    conn.close()\n",
    "\n",
    "def get_statistics():\n",
    "    \"\"\"取得統計資料\"\"\"\n",
    "    today = datetime.date.today()\n",
    "    conn = sqlite3.connect(DB_FILE)\n",
    "    c = conn.cursor()\n",
    "\n",
    "    c.execute('SELECT COUNT(DISTINCT user_id) FROM visitors WHERE date = ?', (today.isoformat(),))\n",
    "    today_count = c.fetchone()[0]\n",
    "\n",
    "    c.execute('SELECT COUNT(DISTINCT user_id) FROM visitors WHERE strftime(\"%Y-%m\", date) = ?', (today.strftime(\"%Y-%m\"),))\n",
    "    month_count = c.fetchone()[0]\n",
    "\n",
    "    c.execute('SELECT COUNT(DISTINCT user_id) FROM visitors WHERE strftime(\"%Y\", date) = ?', (today.strftime(\"%Y\"),))\n",
    "    year_count = c.fetchone()[0]\n",
    "\n",
    "    c.execute('SELECT COUNT(DISTINCT user_id) FROM visitors')\n",
    "    total_count = c.fetchone()[0]\n",
    "\n",
    "    conn.close()\n",
    "    return today_count, month_count, year_count, total_count\n",
    "\n",
    "def plot_recent_visits():\n",
    "    \"\"\"繪製最近7日訪問圖\"\"\"\n",
    "    today = datetime.date.today()\n",
    "    seven_days_ago = today - datetime.timedelta(days=6)\n",
    "\n",
    "    conn = sqlite3.connect(DB_FILE)\n",
    "    c = conn.cursor()\n",
    "    c.execute('''\n",
    "        SELECT date, COUNT(DISTINCT user_id) as users\n",
    "        FROM visitors\n",
    "        WHERE date >= ?\n",
    "        GROUP BY date\n",
    "        ORDER BY date\n",
    "    ''', (seven_days_ago.isoformat(),))\n",
    "    rows = c.fetchall()\n",
    "    conn.close()\n",
    "\n",
    "    if rows:\n",
    "        df = pd.DataFrame(rows, columns=[\"date\", \"users\"])\n",
    "        fig, ax = plt.subplots(figsize=(8, 3))\n",
    "        ax.plot(df[\"date\"], df[\"users\"], marker=\"o\")\n",
    "        ax.set_xlabel(\"日期\")\n",
    "        ax.set_ylabel(\"不同使用者數\")\n",
    "        ax.set_title(\"最近7日不同使用者訪問量\")\n",
    "        ax.grid(True)\n",
    "        st.pyplot(fig)\n",
    "    else:\n",
    "        st.info(\"最近7天尚無訪問紀錄。\")\n",
    "\n",
    "def track():\n",
    "    \"\"\"主控制函數：追蹤並顯示結果\"\"\"\n",
    "    # 初始化資料庫\n",
    "    init_db()\n",
    "\n",
    "    # 取得 user_id（用 query string 模擬）\n",
    "    query_params = st.query_params\n",
    "    user_id = query_params.get(\"user\", [\"unknown\"])[0]\n",
    "    # 記錄訪問\n",
    "    record_visit(user_id)\n",
    "\n",
    "    # 顯示統計在側邊欄\n",
    "    today_count, month_count, year_count, total_count = get_statistics()\n",
    "    with st.sidebar:\n",
    "        st.markdown(\"---\")\n",
    "        st.caption(f\"**🔎 不同使用者統計**\")\n",
    "        st.caption(f\"今日訪問：{today_count:,} 人\")\n",
    "        st.caption(f\"本月訪問：{month_count:,} 人\")\n",
    "        st.caption(f\"今年訪問：{year_count:,} 人\")\n",
    "        st.caption(f\"總訪問：{total_count:,} 人\")\n",
    "\n",
    "    # 畫最近7日流量圖\n",
    "    st.subheader(\"最近7日不同使用者訪問量\")\n",
    "    plot_recent_visits()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
